# Generated by Django 4.2.17 on 2025-01-06 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import track.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('item_ref_kcal', models.PositiveIntegerField()),
                ('item_ref_val', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ('item_name',),
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(max_length=100)),
                ('nutrient_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QtyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_quantity', models.PositiveIntegerField()),
                ('qty_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.item')),
            ],
            options={
                'ordering': ('qty_item', 'qty_quantity'),
            },
        ),
        migrations.CreateModel(
            name='ItemNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemnut_val', models.DecimalField(decimal_places=1, max_digits=4)),
                ('itemnut_ref_val', models.PositiveIntegerField(default=100)),
                ('itemnut_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='track.nutrient')),
                ('itemnut_ref_unit', models.ForeignKey(default=track.models.Unit.get_default_unit, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='nutrients_ref', to='track.unit')),
                ('itemnut_unit', models.ForeignKey(default=track.models.Unit.get_default_unit, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='nutrients', to='track.unit')),
            ],
            options={
                'ordering': ('itemnut_name__nutrient_name', 'itemnut_val'),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_nutrients',
            field=models.ManyToManyField(blank=True, to='track.itemnutrient'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(default=track.models.Unit.get_default_unit, on_delete=django.db.models.deletion.SET_DEFAULT, to='track.unit'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(blank=True, max_length=500, null=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_main', models.BooleanField(default=False)),
                ('entry_total_kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_items', models.ManyToManyField(blank=True, to='track.qtyitem')),
            ],
        ),
    ]
