# Generated by Django 4.2.17 on 2025-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnutrient',
            name='itemnut_val',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
