# Generated by Django 4.2.17 on 2025-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_itemnutrient_itemnut_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnutrient',
            name='itemnut_val',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
