# Generated by Django 5.2.9 on 2025-12-31 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_itemnutrient_itemnut_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtyitem',
            name='qty_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='track.item'),
        ),
    ]
