# Generated by Django 5.2.9 on 2025-12-31 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_qtyitem_qty_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtyitem',
            name='qty_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.item'),
        ),
    ]
