# Generated by Django 5.2.9 on 2026-01-01 08:42

import django.db.models.deletion
import track.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_alter_qtyitem_qty_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnutrient',
            name='itemnut_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='track.nutrient'),
        ),
        migrations.AlterField(
            model_name='itemnutrient',
            name='itemnut_ref_unit',
            field=models.ForeignKey(default=track.models.Unit.get_default_unit, on_delete=django.db.models.deletion.PROTECT, related_name='nutrients_ref', to='track.unit'),
        ),
        migrations.AlterField(
            model_name='itemnutrient',
            name='itemnut_unit',
            field=models.ForeignKey(default=track.models.Unit.get_default_unit, on_delete=django.db.models.deletion.PROTECT, related_name='nutrients', to='track.unit'),
        ),
    ]
